import { IsOptional, IsString, Matches, MinLength } from 'class-validator';

export class WidgetMessageDto {
  @IsString()
  @MinLength(1)
  question: string;

  // Generated by the widget once per message and resent unchanged if the socket reconnects and
  // re-sends it — the same role Idempotency-Key plays for /ask. Optional: an older widget
  // build without it still works, just without duplicate protection.
  @IsOptional()
  @Matches(/^[A-Za-z0-9_\-.:]{1,100}$/)
  clientMessageId?: string;
}
