import { readFileSync } from 'fs';
import { join } from 'path';
import { extractText, isEffectivelyEmpty, UnsupportedMimeTypeError } from './extraction';

const fixture = (name: string) => readFileSync(join(__dirname, 'fixtures', name));

describe('extractText (dispatcher)', () => {
  it('dispatches application/pdf to the PDF extractor', async () => {
    const result = await extractText(fixture('sample.pdf'), 'application/pdf');

    expect(result.text).toContain('Hello World from a real test PDF generated by headless Chrome.');
  });

  it('dispatches the DOCX mime type to the DOCX extractor', async () => {
    const result = await extractText(
      fixture('sample.docx'),
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    );

    expect(result.text).toContain('Hello World from a hand-built DOCX fixture.');
  });

  it('throws UnsupportedMimeTypeError for a mime type with no registered extractor', async () => {
    await expect(extractText(Buffer.from('irrelevant'), 'image/png')).rejects.toThrow(
      UnsupportedMimeTypeError,
    );
  });
});

describe('isEffectivelyEmpty', () => {
  it('treats an empty string as effectively empty', () => {
    expect(isEffectivelyEmpty('')).toBe(true);
  });

  it('treats whitespace-only text as effectively empty', () => {
    expect(isEffectivelyEmpty('   \n\n\t  ')).toBe(true);
  });

  it('treats text just under the meaningful-length threshold as effectively empty', () => {
    expect(isEffectivelyEmpty('short text, thirty nine chars long!!!!')).toBe(true);
  });

  it('treats text at or above the meaningful-length threshold as not empty', () => {
    expect(isEffectivelyEmpty('this sentence is deliberately over forty characters long')).toBe(
      false,
    );
  });

  it('classifies real extracted PDF body text as not empty', async () => {
    const result = await extractText(fixture('sample.pdf'), 'application/pdf');
    expect(isEffectivelyEmpty(result.text)).toBe(false);
  });
});
