import { readFileSync } from 'fs';
import { join } from 'path';
import { extractPdfText } from './pdf-extractor';

const fixture = (name: string) => readFileSync(join(__dirname, 'fixtures', name));

describe('extractPdfText', () => {
  it('extracts real text and a page count from a genuine PDF', async () => {
    const result = await extractPdfText(fixture('sample.pdf'));

    expect(result.text).toContain('Hello World from a real test PDF generated by headless Chrome.');
    expect(result.pageCount).toBe(1);
  });

  it('returns whatever text is embedded even when the page has no real body content', async () => {
    // This fixture is an image-only page (no <p>/<span> text at all) printed via headless
    // Chrome. Chrome's own print pipeline still stamps a date/url/page-number footer into
    // the PDF regardless of page content, so this is NOT literally zero text (a real
    // photographed/scanned PDF from a scanner has zero) — but it proves none of the *page's*
    // content made it into the extracted text, which is the behavior that matters here.
    const result = await extractPdfText(fixture('scanned.pdf'));

    expect(result.text).not.toContain('Hello World');
    expect(result.text.trim().length).toBeLessThan(100);
  });
});
